### ISSUE TITLE
Error netatmo

### ISSUE THREAD

**Issue by doreks** [potsky/Netatmo#22]
any idea about these errors:

`2018-11-03 09:49:08 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/netatmo.py", line 50, in setup_platform
    for module_name in data.get_module_names():
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/climate/netatmo.py", line 164, in get_module_names
    for module in self.thermostatdata.modules[self.device].values():
KeyError: 'salon'
2018-11-03 09:49:08 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/netatmo.py", line 80, in setup_platform
    if module_name not in data.get_module_names():
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/netatmo.py", line 304, in get_module_names
    self.update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/sensor/netatmo.py", line 333, in update
    for module in self.data:
TypeError: 'NoneType' object is not iterable
2018-11-03 09:49:08 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/binary_sensor/netatmo.py", line 73, in setup_platform
    if not data.get_camera_names():
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/netatmo.py", line 82, in get_camera_names
    self.update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/netatmo.py", line 113, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/srv/homeassistant/lib/python3.5/site-packages/smart_home/Camera.py", line 79, in __init__
    self.default_camera = list(self.cameras[self.default_home].values())[0]
AttributeError: 'CameraData' object has no attribute 'default_home'
2018-11-03 09:49:11 ERROR (MainThread) [homeassistant.components.camera] Error while setting up platform netatmo
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/camera/netatmo.py", line 40, in setup_platform
    for camera_name in data.get_camera_names():
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/netatmo.py", line 82, in get_camera_names
    self.update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/netatmo.py", line 113, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/srv/homeassistant/lib/python3.5/site-packages/smart_home/Camera.py", line 79, in __init__
    self.default_camera = list(self.cameras[self.default_home].values())[0]
AttributeError: 'CameraData' object has no attribute 'default_home'`

i have this setup into configuration.yaml

`netatmo:
  api_key: 58***********6
  secret_key: 11****************X
  username: mail@mail.com
  password: password

climate:
  platform: netatmo
  relay: salon
  thermostat:
    - Salon`
`  - platform: netatmo
    station: Alcortwo Weather
    modules:
         indoor salon:
          - temperature
          - co2
          - pressure
          - noise
          - humidity
          - wifi_status
         alcortwo outside:
          - temperature
          - humidity
          - battery_vp

  - platform: yr

  - platform: time_date
    display_options:
     - 'time'
     - 'date'`

**Comment by doreks** [comment]
any idea¿?

**Comment by potsky** [comment]
Hi @aocana !

as written on the GitHub home page of the repo, this code is NO MORE SUPPORTED :-(

API has change last year and I have no more time to rewrite it.

Regards

potsky

**Comment by doreks** [comment]
uppsss bad news.. :-(
what is the alternative?
